services:
  discord-bot:
    build: .
    container_name: discord-bot
    ports:
      - "8090:8090"
    environment:
      - RU_EXAMPLE_STT_MODEL_PATH=${RU_EXAMPLE_STT_MODEL_PATH}  # ะะท .env!
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
    stdin_open: true
    tty: true
    restart: unless-stopped
